### ISSUE TITLE
STMPE610 problem

### ISSUE THREAD

**Issue by yk9** [adafruit/Adafruit_STMPE610#11]
im using IAR project , based ili9341 gfx and i added the SMPTE610, but i cant get the chip to response. i want the basic test of getting the ID (send 0x00 response 0x0811)or VER(0x02 response 0x01), but no luck. did any one had this problem?

![scope_4](https://user-images.githubusercontent.com/15733685/45074109-da884680-b0ea-11e8-8f5e-bf9752c5a9c7.jpg)

**Comment by ladyada** [comment]
we've never used IAR but check you're trying both MODE1 and MODE0, stmpe can come up in either mode depending on pin states (check datasheet for exact, its been many years since we wrote the code :)

**Comment by yk9** [comment]
ok , i can read it registers im writing to , also ID and VER 
but no values from XY registers. i followed to example initialization, also the touch detection bit is not changing. any ideas?
