### ISSUE TITLE
Does not work with Teensy 3.6

### ISSUE THREAD

**Issue by Rababermaber** [adafruit/Adafruit_STMPE610#12]
I tried the Library on a Teensy 3.6 and it doesn't work. So I tested some stuff out and got it to work unreliably with the clock frequency lowered to 120Mhz or 96Mhz. I also hooked the DOUT up to my oscilloscope and found out that the CLK frequency was always at 1Mhz at all clock frequencies including 180Mhz and 240Mhz.

**Comment by Rababermaber** [comment]
I located the problem: Everything works when I initialize the IC with the Teensy 3.6 set to 96Mhz, and then comment out the initialisation commands and setting the Teensy back to 180Mhz. So there is somehow a problem with initialising the STMPE610 when the Teensy is set to 180Mhz(above 96/120Mhz).

**Comment by ladyada** [comment]
we've done quite a refactor, this is likely fixed? please try it and reopen if still an issue

**Comment by BlueGene00** [comment]
Hello,
I have also tried the 3.5" Feather TFT (Library version 1.1.0) with a Teensy 3.6 and the touch function does not work... With an Feather M0 it works without issues.

I have found this topic here and added the delays:
https://forum.pjrc.com/threads/54982-TEENSY-3-6-ADAFRUIT-3-5-quot-TFT-touch-controller-issue

Now it works some kind of, but there are some issues and it is not 100% reliable.

Please check the libary with a Teensy 3.6.

**Comment by ladyada** [comment]
tanks, please submit a PR with the delays you have added!
