### ISSUE TITLE
Hardware SPI Issue

### ISSUE THREAD

**Issue by bjun626** [adafruit/Adafruit_STMPE610#20]
In [Adafruit_STMPE610.cpp](https://github.com/adafruit/Adafruit_STMPE610/blob/9a0e2823d89ac5a099b66719c5dcae928d9445ba/Adafruit_STMPE610.cpp#L284) Line 284, should be using **_spi->** instead of **SPI**.

This issue caused HW SPI unable to return the Semaphore which prevents future transactions.

**Comment by ladyada** [comment]
hihi sounds like a typo slipped through - can you submit a PR for the fix?

**Comment by ladyada** [comment]
thanks :)
