### ISSUE TITLE
Touch Interrupt on STMPE610

### ISSUE THREAD

**Issue by gurtajs4** [adafruit/Adafruit_STMPE610#5]
Hi Sir,

I am using https://www.adafruit.com/products/1601 LDC Display to interface with Raspberry Pi.
I am not using kernel drivers to access the controller, but rather using Python based Libaries to Initialize the ILI9341 and STMPE610.

I am facing issue with getting touch interrupt on a particular GPIO.
I would like to connect multiple Display to RPi using SPIDEV, different Chip Select  and GPIO pin to control LCD and Touch

For this to work, I want to get interrupt from a TS on a particular GPIO Pin, when user touch that display, and hence data can be drive accordingly to display.

Can you point me to some C/Python Sample to achieve this.
Thanks 
Gurtaj

**Comment by ladyada** [comment]
this library is in C so you can use it to adapt to raspi userspace. we don't have any other python or raspi code since we use the kerneldriver!
